import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {rankGroups} from '../../src/lib/hearth/matching';
import type {HearthState} from '../../src/lib/hearth/domain';

test('three departed residents each receive a decision and preserve their stay through reload and withdrawal', async ({page}) => {
  await page.goto('/find');
  const contentResponse = await page.request.get('/api/content');
  expect(contentResponse.ok()).toBe(true);
  const payload = await contentResponse.json() as {state:HearthState;mode:string};
  const state = payload.state;
  const scenario = state.homes.flatMap((home,index)=>home.preferences.departedCapacity != null && home.preferences.departedCapacity >= 3 ? rankGroups(state,home.preferences,['quiet-hours'],3).filter(group=>group.status==='eligible' && group.consentRequirements?.every(requirement=>requirement.kind==='household'||requirement.kind==='adult')).map(group=>({home,index,group})) : [])[0];
  expect(scenario,'An explicit-capacity household can review three adult departed residents').toBeTruthy();
  const {home,index:homeIndex,group}=scenario;
  await page.getByRole('button',{name:new RegExp('CASE 00'+(homeIndex+1))}).click();
  await page.getByRole('button',{name:/see its possible (pairings|placements) now/}).click();
  await expect(page).toHaveURL(/\/matches$/);
  await page.getByRole('radio',{name:'3 residents'}).check();
  await expect(page.getByRole('radio',{name:'3 residents'})).toBeChecked();

  await page.goto('/match/'+group!.spiritIds.join('~'));
  await expect(page.getByRole('button',{name:'Review an introduction'})).toBeVisible();
  if(group!.negotiations.length) await page.getByRole('checkbox').check();
  await expect(page.getByRole('button',{name:'Review an introduction'})).toBeEnabled();
  await page.getByRole('button',{name:'Review an introduction'}).click();
  await expect(page).toHaveURL(/\/stay\//);
  await expect(page.locator('#consents article')).toHaveCount(4);
  await expect(page.getByRole('button',{name:'Begin trial stay'})).toBeDisabled();
  await page.getByRole('button',{name:'Save trial & relocation plan'}).click();
  const answers = page.getByRole('button',{name:/^Record yes for/});
  await expect(answers.first()).toBeEnabled();
  for(let index=0;index<await answers.count();index++) await answers.nth(index).click();
  const consents = page.getByRole('button',{name:/^Record agreement for/});
  await expect(consents).toHaveCount(4);
  for(let index=0;index<3;index++) await consents.nth(index).click();
  await expect(page.getByRole('button',{name:'Begin trial stay'})).toBeDisabled();
  await consents.nth(3).click();
  await expect(page.getByRole('button',{name:'Begin trial stay'})).toBeEnabled();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const accessibility = await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
  expect(accessibility.violations.map(violation=>({id:violation.id,nodes:violation.nodes.map(node=>node.target)}))).toEqual([]);
  await page.screenshot({path:'.tmp/final-pass-group-mobile.png',fullPage:true});
  await page.locator('#consents').screenshot({path:'.tmp/final-pass-group-consents-mobile.png'});
  await page.getByRole('button',{name:'Begin trial stay'}).click();
  await expect(page.getByRole('heading',{name:'Trial stay',exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Trial stay',exact:true})).toBeVisible();
  await expect(page.locator('#consents article')).toHaveCount(4);
  const thirdName = state.spirits.find(spirit=>spirit.id===group!.spiritIds[2])!.name;
  await page.getByRole('button',{name:'Record withdrawal for '+thirdName}).click();
  await expect(page.getByRole('heading',{name:'Relocation plan',exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Relocation plan',exact:true})).toBeVisible();
  const saved = await page.evaluate(()=>JSON.parse(localStorage.getItem('hearthafter-household-v1')!));
  expect(saved.placements[0].spiritIds).toHaveLength(3);
  expect(Object.keys(saved.placements[0].consents)).toHaveLength(4);
  await page.goto('/visits');
  const heading=page.getByRole('heading',{level:2}).filter({hasText:thirdName});
  await expect(heading).toBeVisible();
  for(const id of group.spiritIds) await expect(heading).toContainText(state.spirits.find(spirit=>spirit.id===id)!.name);
});


test('an intact departed family needs guardian care and separate child assent, and refusal ends the proposal', async ({page}) => {
  await page.goto('/find');
  const response=await page.request.get('/api/content');
  expect(response.ok()).toBe(true);
  const {state}=await response.json() as {state:HearthState};
  const ids=['spirit_mara_aster','spirit_leon_aster','spirit_kit_aster'];
  const scenario=state.homes.flatMap((home,index)=>home.preferences.departedCapacity != null && home.preferences.departedCapacity>=3 ? rankGroups(state,home.preferences,['quiet-hours'],3).filter(group=>group.status==='eligible'&&ids.every(id=>group.spiritIds.includes(id))).map(group=>({home,index,group})) : [])[0];
  expect(scenario,'An offered three-resident household can keep the documented family together').toBeTruthy();
  await page.getByRole('button',{name:new RegExp('CASE 00'+(scenario.index+1))}).click();
  await page.getByRole('button',{name:/see its possible (pairings|placements) now/}).click();
  await page.getByRole('radio',{name:'3 residents'}).check();
  const path='/match/'+encodeURIComponent(scenario.group.spiritIds.join('~'));
  if(!await page.locator(`a[href="${path}"]`).count()) await page.getByRole('button',{name:/See all/}).click();
  await page.locator(`a[href="${path}"]`).click();
  await expect(page.getByRole('button',{name:'Review an introduction'})).toBeVisible();
  if(scenario.group.negotiations.length) await page.getByRole('checkbox').check();
  await page.getByRole('button',{name:'Review an introduction'}).click();
  await expect(page).toHaveURL(/\/stay\//);
  await expect(page.locator('#consents article')).toHaveCount(5);
  await expect(page.locator('#consents')).toContainText('care agreement for Kit Aster');
  await expect(page.locator('#consents')).toContainText('Kit Aster: age-appropriate assent');
  await page.getByRole('button',{name:'Save trial & relocation plan'}).click();
  const answers=page.getByRole('button',{name:/^Record yes for/});
  await expect(answers.first()).toBeEnabled();
  for(let index=0;index<await answers.count();index++) await answers.nth(index).click();
  const agreement=page.getByRole('button',{name:/^Record agreement for/});
  for(let index=0;index<await agreement.count();index++) {
    const label=await agreement.nth(index).getAttribute('aria-label');
    if(!label?.includes('age-appropriate assent')) await agreement.nth(index).click();
  }
  await expect(page.getByRole('button',{name:'Begin trial stay'})).toBeDisabled();
  await page.reload();
  await expect(page.locator('#consents article')).toHaveCount(5);
  await expect(page.getByRole('button',{name:'Begin trial stay'})).toBeDisabled();
  await page.getByRole('button',{name:'Record refusal for Kit Aster: age-appropriate assent'}).click();
  await expect(page.getByRole('heading',{name:'Introduction declined',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:/Record agreement/})).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Introduction declined',exact:true})).toBeVisible();
});
