import {test,expect,type Page,type TestInfo} from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import type {SavedVisit} from "../../src/lib/hearth/saved-visit";
async function checkAccessibility(page:Page,testInfo:TestInfo,label:string){
 expect.soft(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`Horizontal overflow at ${label}`).toBe(true);
 const result=await new AxeBuilder({page}).withTags(["wcag2a","wcag2aa","wcag21aa"]).analyze();
 if(result.violations.length)await testInfo.attach("accessibility-"+label,{body:JSON.stringify(result.violations,null,2),contentType:"application/json"});
 expect.soft(result.violations.map(v=>({id:v.id,targets:v.nodes.map(n=>({target:n.target,summary:n.failureSummary}))})),`Accessibility at ${label}`).toEqual([]);
}
async function chooseJune(page:Page){
 await page.goto("/find");
 await page.getByRole("button",{name:/CASE 001 June/}).click();
 await page.getByRole("button",{name:/see its possible (pairings|placements) now/}).click();
 await expect(page).toHaveURL(/\/matches$/);
 await page.goto("/match/spirit_iona_vale~spirit_orin_pell");
 await expect(page.getByRole("button",{name:"Review an introduction"})).toBeDisabled();
 await page.getByRole("checkbox").check();
 await expect(page.getByRole("button",{name:"Review an introduction"})).toBeEnabled();
}
async function openReview(page:Page){
 await chooseJune(page);await page.getByRole("button",{name:"Review an introduction"}).click();await expect(page).toHaveURL(/\/stay\//);
 await expect(page.getByRole("button",{name:"Begin trial stay"})).toBeDisabled();
}
test("an honest comparison keeps Noor's camera boundary separate from preference scores",async({page})=>{
 await chooseJune(page);
 await page.getByLabel("COMPARE A HOUSEHOLD").selectOption("household_noor");
 await expect(page.getByText("A boundary comes first",{exact:true})).toBeVisible();
 await expect(page.getByText(/Orin.*camera|camera.*Orin/).first()).toBeVisible();
 await page.getByRole("button",{name:"Use this household"}).click();
 await expect(page.getByRole("button",{name:"Review an introduction"})).toBeDisabled();
 await page.reload();
 await expect(page.getByRole("button",{name:"Review an introduction"})).toBeDisabled();
});
test("a complete local review persists through reload and respects withdrawal",async({page})=>{
 await openReview(page);
 await page.getByRole("button",{name:"Save trial & relocation plan"}).click();
 const confirmations=page.getByRole("button",{name:/^Record yes for/});
 await expect(confirmations.first()).toBeEnabled();
 const count=await confirmations.count();expect(count).toBeGreaterThan(0);
 const readinessLinks=page.locator("#next-step").getByRole("link",{name:/^Question \d+:/});
 const requiredCount=await page.locator("#introductions article").filter({hasText:"REQUIRED FOR A TRIAL"}).count();
 await expect(readinessLinks).toHaveCount(requiredCount);
 await expect(page.locator("#next-step")).not.toContainText("Resolve every required introduction question");
 const firstQuestionId=decodeURIComponent((await readinessLinks.first().getAttribute("href"))!.slice(1));
 await readinessLinks.first().click();
 await expect(page.locator("[id=\""+firstQuestionId+"\"]")).toBeFocused();
 for(let index=0;index<count;index++)await confirmations.nth(index).click();
 const consents=page.getByRole("button",{name:/^Record agreement for/});
 await expect(consents.first()).toBeEnabled();
 for(let index=0;index<await consents.count();index++)await consents.nth(index).click();
 await expect(page.getByRole("button",{name:"Begin trial stay"})).toBeEnabled();
 const requiredQuestion=page.locator("#introductions article").filter({hasText:"REQUIRED FOR A TRIAL"}).first();
 await requiredQuestion.getByRole("button",{name:/^Record still unknown for/}).click();
 await expect(page.locator("#consents").getByText("Awaiting a decision",{exact:true})).toHaveCount(3);
 await expect(consents.first()).toBeDisabled();
 await expect(page.getByRole("button",{name:"Begin trial stay"})).toBeDisabled();
 await page.reload();
 await expect(requiredQuestion.getByRole("button",{name:/^Record still unknown for/})).toHaveAttribute("aria-pressed","true");
 await expect(page.locator("#consents").getByText("Awaiting a decision",{exact:true})).toHaveCount(3);
 await requiredQuestion.getByRole("button",{name:/^Record yes for/}).click();
 await expect(consents.first()).toBeEnabled();
 for(let index=0;index<await consents.count();index++)await consents.nth(index).click();
 await expect(page.getByRole("button",{name:"Begin trial stay"})).toBeEnabled();
 const caseURL=page.url();
 await page.getByRole("button",{name:"Begin trial stay"}).click();
 await expect(page.getByRole("heading",{name:"Trial stay",exact:true})).toBeVisible();
 await page.reload();
 await expect(page.getByRole("heading",{name:"Trial stay",exact:true})).toBeVisible();
 await page.getByRole("link",{name:/Your cases/}).click();
 await expect(page.getByRole("link",{name:/Continue/}).first()).toHaveAttribute("href",new URL(caseURL).pathname);
 await page.getByRole("link",{name:/Continue/}).first().click();
 await expect(page.getByRole("button",{name:"Record trial outcome"})).toBeDisabled();
 await page.getByLabel("Trial outcome").fill("All residents and both spirits confirm comfortable quiet hours, respected retreats and a voluntary wish to continue after the final check-in.");
 await page.getByRole("button",{name:"Record trial outcome"}).click();
 await expect(page.getByRole("heading",{name:"Settled placement",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"Record withdrawal for Orin Pell"}).click();
 await expect(page.getByRole("heading",{name:"Relocation plan",exact:true})).toBeVisible();
 await page.getByLabel("Handover outcome").fill("Both spirits moved to the confirmed interim rooms with their keepsakes. The duty coordinator completed separate check-ins.");
 await page.getByRole("button",{name:"Record handover & close"}).click();
 await expect(page.getByRole("heading",{name:"Case closed",exact:true})).toBeVisible();
 await page.reload();await expect(page.getByRole("heading",{name:"Case closed",exact:true})).toBeVisible();
});
test("refusal is final and an invalid plan cannot create permission",async({page})=>{
 await openReview(page);
 await page.getByLabel(/Trial length/).fill("6");
 await page.getByRole("button",{name:"Save trial & relocation plan"}).click();
 await expect(page.getByRole("button",{name:"Begin trial stay"})).toBeDisabled();
 await page.getByRole("button",{name:"Record refusal for Iona Vale"}).click();
 await expect(page.getByRole("heading",{name:"Introduction declined",exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:/Record agreement/})).toHaveCount(0);
 await page.reload();await expect(page.getByRole("heading",{name:"Introduction declined",exact:true})).toBeVisible();
});
test("a failed registry refresh blocks new commitments while preserving withdrawal",async({page})=>{
 await page.clock.install();
 await openReview(page);
 await page.getByRole("button",{name:"Save trial & relocation plan"}).click();
 const confirmations=page.getByRole("button",{name:/^Record yes for/});
 await expect(confirmations.first()).toBeEnabled();
 const count=await confirmations.count();expect(count).toBeGreaterThan(0);
 for(let index=0;index<count;index++)await confirmations.nth(index).click();
 const consents=page.getByRole("button",{name:/^Record agreement for/});
 await expect(consents.first()).toBeEnabled();
 for(let index=0;index<await consents.count();index++)await consents.nth(index).click();
 const beginTrial=page.getByRole("button",{name:"Begin trial stay"});
 await expect(beginTrial).toBeEnabled();
 async function failRegistryRefresh(){
  await page.route("**/api/content",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:"The registry connection failed during this review."})}));
  const refresh=page.waitForResponse(response=>response.url().endsWith("/api/content")&&response.status()===503);
  await page.clock.fastForward(16000);
  await refresh;
  await expect(page.getByRole("alert").filter({hasText:"The registry connection failed during this review."})).toBeVisible();
 }
 await failRegistryRefresh();
 await expect(beginTrial).toBeDisabled();
 await page.unroute("**/api/content");
 const restored=page.waitForResponse(response=>response.url().endsWith("/api/content")&&response.ok());
 await page.getByRole("button",{name:"Try again",exact:true}).click();
 await restored;
 await expect(beginTrial).toBeEnabled();
 await beginTrial.click();
 await expect(page.getByRole("heading",{name:"Trial stay",exact:true})).toBeVisible();
 await page.getByLabel("Trial outcome").fill("All residents and spirits report respected boundaries and a voluntary wish to continue after their final fictional check-in.");
 const settle=page.getByRole("button",{name:"Record trial outcome"});
 await expect(settle).toBeEnabled();
 const beforeWithdrawal=await page.evaluate(()=>JSON.parse(localStorage.getItem("hearthafter-household-v1")!) as SavedVisit);
 await failRegistryRefresh();
 await expect(page.getByText("Saved record · current sources unverified",{exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:"Confirm settled placement",exact:true})).toBeDisabled();
 await expect(page.getByRole("button",{name:"Record agreement",exact:true})).toBeDisabled();
 await page.getByLabel("Whose decision?").selectOption({label:"Orin Pell"});
 const withdrawalNote="Orin freely withdraws from this stay and asks to use the saved exit arrangements.";
 await page.getByLabel("Refusal or withdrawal note").fill(withdrawalNote);
 const withdraw=page.getByRole("button",{name:"Record withdrawal locally",exact:true});
 await expect(withdraw).toBeEnabled();
 await withdraw.click();
 await expect(page.getByText(/Refusal or withdrawal recorded in this browser/)).toBeVisible();
 const withdrawn=await page.evaluate(()=>JSON.parse(localStorage.getItem("hearthafter-household-v1")!) as SavedVisit);
 expect(withdrawn.placements[0].status).toBe("relocating");
 expect(withdrawn.placements[0].consents["spirit-b"]).toMatchObject({decision:"denied",note:withdrawalNote});
 expect(withdrawn.placements[0].relocationPlan).toEqual(beforeWithdrawal.placements[0].relocationPlan);
 expect(withdrawn.placements[0].trialPlan).toEqual(beforeWithdrawal.placements[0].trialPlan);
 expect(withdrawn.events).toHaveLength(beforeWithdrawal.events.length+1);
 expect(withdrawn.events.at(-1)).toMatchObject({action:"record-consent",fromStatus:"trial",toStatus:"relocating",expectedRev:beforeWithdrawal.placements[0].rev});
 await page.reload();
 await expect(page.getByRole("heading",{name:"Your saved safe exit",exact:true})).toBeVisible();
 await expect(page.getByText(withdrawn.placements[0].relocationPlan!.destination,{exact:true})).toBeVisible();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("hearthafter-household-v1")!))).toEqual(withdrawn);
 await page.unroute("**/api/content");
 await page.getByRole("button",{name:"Try again",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Relocation plan",exact:true})).toBeVisible();
 expect(await page.evaluate(()=>JSON.parse(localStorage.getItem("hearthafter-household-v1")!))).toEqual(withdrawn);
});
test("profile discovery and the reduced-motion introduction work from the keyboard",async({page})=>{
 await page.emulateMedia({reducedMotion:"reduce"});
 await page.goto("/spirits");
 await page.getByRole("searchbox").fill("Iona Vale");
 await expect(page.getByRole("link",{name:"Read Iona Vale's profile"})).toBeVisible();
 await expect(page.getByRole("link",{name:"Read Orin Pell's profile"})).toHaveCount(0);
 await page.getByRole("link",{name:"Read Iona Vale's profile"}).click();
 await expect(page.getByRole("heading",{name:"Iona Vale",exact:true})).toBeVisible();
 await page.goto("/");await page.getByRole("button",{name:/Watch the Overlap/}).click();
 await expect(page.getByRole("dialog")).toBeVisible();await page.keyboard.press("Escape");
 await expect(page.getByRole("dialog")).not.toBeVisible();await expect(page.getByRole("button",{name:/Watch the Overlap/})).toBeFocused();
});
test("a missing registry shows a retry state instead of substituting seed profiles",async({page})=>{
 await page.route("**/api/content",route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({error:"The registry is unavailable for this test."})}));
 for(const route of ["/find","/spirits","/spirits/spirit_iona_vale"]){
  await page.goto(route);
  await expect(page.getByRole("button",{name:"Try the registry again"})).toBeVisible();
  await expect(page.getByRole("button",{name:/CASE 001 June/})).toHaveCount(0);
  await expect(page.getByRole("link",{name:"Read Iona Vale's profile"})).toHaveCount(0);
  await expect(page.getByRole("heading",{name:"Iona Vale",exact:true})).toHaveCount(0);
  await expect(page.getByText("Local preview",{exact:true})).toHaveCount(0);
 }
 await page.unroute("**/api/content");
 await page.getByRole("button",{name:"Try the registry again"}).click();
 await expect(page.getByRole("heading",{name:"Iona Vale",exact:true})).toBeVisible();
 await page.goto("/spirits");
 await expect(page.getByRole("link",{name:"Read Iona Vale's profile"})).toBeVisible();
});
test("mobile navigation, saved answers and important pages remain accessible",async({page},testInfo)=>{
 test.setTimeout(90000);
 await page.setViewportSize({width:390,height:844});
 await page.emulateMedia({reducedMotion:"reduce"});
 await page.goto("/");await page.getByRole("button",{name:"Open navigation"}).click();
 await expect(page.getByRole("navigation",{name:"Main navigation"})).toBeVisible();
 await page.keyboard.press("Escape");
 await expect(page.getByRole("navigation",{name:"Main navigation"})).not.toBeVisible();
 await expect(page.getByRole("button",{name:"Open navigation"})).toBeFocused();
 await page.getByRole("button",{name:"Open navigation"}).click();
 await page.getByRole("link",{name:"Spirit register",exact:true}).click();
 await expect(page).toHaveURL(/\/spirits$/);
 for(const route of ["/","/find","/spirits","/world"]){
  await page.goto(route);await page.waitForLoadState("networkidle");
  await checkAccessibility(page,testInfo,route==="/"?"home":route.slice(1));
 }
 await page.goto("/find");
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Space and boundaries",exact:true})).toBeFocused();
 await page.getByRole("button",{name:"Continue",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Daily routines",exact:true})).toBeFocused();
 await page.getByRole("button",{name:"Back",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Space and boundaries",exact:true})).toBeFocused();
 await chooseJune(page);
 await checkAccessibility(page,testInfo,"pair-review");
 await page.getByRole("button",{name:"Review an introduction"}).click();
 await expect(page.getByRole("button",{name:"Begin trial stay"})).toBeDisabled();
 await page.getByRole("button",{name:"Save trial & relocation plan"}).click();
 await expect(page.getByRole("button",{name:/^Record yes for/}).first()).toBeEnabled();
 await checkAccessibility(page,testInfo,"placement-review");
});
