"use client";
import Link from "next/link";
import Image from "next/image";
import {ArrowRight,BookOpen,Check,DoorOpen,Heart,House,ShieldCheck} from "lucide-react";
import {SiteHeader,SiteFooter,RegistryNotice} from "./site-shell";
import {IntroFilmButton} from "./intro-film";
import {useArtwork} from "./use-artwork";
export function HomePage(){
 const art=useArtwork();
 return <><SiteHeader/><RegistryNotice/><main id="main" className="service-home">
  <div className="service-reference"><span>HEARTHAFTER / RESIDENTIAL PLACEMENT</span><span>SERVICE H-01</span></div>
  <section className="civic-hero" aria-labelledby="hero-title">
   <div className="civic-hero-copy"><span className="eyebrow">VOLUNTARY HOST REGISTRATION</span><h1 id="hero-title">Share your home<br/><em>with the departed.</em></h1><p className="civic-hero-lead">The Overlap brought a sudden population of departed residents into everyday life. Hearthafter connects willing living households with groups who need a home, with company, privacy and a safe way to leave.</p><div className="civic-hero-actions"><Link href="/find" className="button button-pine">Begin host application <ArrowRight size={18}/></Link><Link href="/spirits" className="underlined-link">Browse the spirit register <ArrowRight size={15}/></Link></div><p className="service-privacy"><Check size={14}/> No account required. Your answers stay on this device.</p><div className="service-assurance"><ShieldCheck size={23}/><p><strong>No departed resident is placed alone.</strong>At least two departed residents, a willing living household, and an individual review before any stay.</p></div></div>
   <figure className="civic-hero-figure"><div className="figure-register"><span>OFFICE FIELD GUIDE</span><span>HOME & COMMUNITY / 01</span></div><div className="welcome-photo">{art?<Image src={art.heroUrl} alt="Two hosts welcome two departed residents onto a warmly lit porch." width={1672} height={941} sizes="(max-width:760px) 92vw, 52vw" loading="eager" quality={75}/>:<div className="art-placeholder" role="status">Opening the field guide.</div>}</div><figcaption><span>Good company.<br/><em>A place to haunt.</em></span><span className="placement-mark"><House size={21}/><small>ROOM FOR<br/>ONE ANOTHER</small></span></figcaption></figure>
  </section>
  <section className="service-steps" id="placement-steps" aria-label="The placement process">{[{number:"01",label:"YOUR HOUSEHOLD",title:"Describe your household.",detail:"Your daily rhythm, the space you can offer, and the boundaries that matter.",href:"/find",link:"Start an application"},{number:"02",label:"THE PROPOSED RESIDENTS",title:"Meet the proposed residents.",detail:"Browse without applying. Get to know their stories, routines and relationships before considering a group.",href:"/spirits",link:"Open the spirit register"},{number:"03",label:"A SHARED AGREEMENT",title:"Agree the terms of a trial.",detail:"Agree on the details, check in along the way, and keep a clear path forward.",href:"/world#ground-rules",link:"Read the placement guide"}].map(step=><article key={step.number}><div className="service-step-index"><span>{step.number}</span><small>{step.label}</small></div><h2>{step.title}</h2><p>{step.detail}</p><Link href={step.href}>{step.link}<ArrowRight size={14}/></Link></article>)}</section>
  <section className="service-before"><div><span className="eyebrow">BEFORE YOU BEGIN</span><h2>Before you<br/><em>offer a room.</em></h2><p>You will be asked about sleeping hours, pets, shared spaces and privacy. You can leave an answer open if it needs a conversation.</p></div><ul><li><Heart size={22}/><span><strong>Every adult has a say.</strong>Everyone living in the household should be willing to explore an introduction.</span></li><li><DoorOpen size={22}/><span><strong>Make room for privacy.</strong>Consider a retreat, everyday routines, and which parts of the home stay private.</span></li><li><ShieldCheck size={22}/><span><strong>Keep the next step open.</strong>A trial needs a shared plan and a safe place to go if the arrangement ends.</span></li></ul></section>
  <section className="service-field-note"><div className="service-field-icon"><BookOpen size={33}/><span>FIELD NOTE<br/>THE OVERLAP</span></div><div><span className="eyebrow">FROM THE OFFICE ARCHIVE</span><h2>How the Overlap<br/><em>changed the address book.</em></h2><p>New generation systems and major transmission infrastructure were built for Ashburn's Data Center Alley and its immense electricity demand. Their unexpected combined effect made the departed visible, first in Northern Virginia and then beyond.</p><div className="field-note-actions"><Link href="/world" className="underlined-link">Read about the Overlap <ArrowRight size={15}/></Link><IntroFilmButton assets={art?{grid:art.overlapUrl,overlap:art.overlapUrl,welcome:art.heroUrl,hearth:art.heroUrl}:undefined} disabled={!art}/><Link href="/about#technical-tour" className="underlined-link">Behind the service <ArrowRight size={15}/></Link></div></div></section>
 </main><SiteFooter/></>;
}
