"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useMemo,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,Check,MessagesSquare,ShieldCheck} from "lucide-react";
import type {HearthState,HostPreferences,MatchReason,PairEvaluation,Spirit} from "@/lib/hearth/domain";
import {evaluatePair,rankGroups,stableSerialize} from "@/lib/hearth/matching";
import {newRequestId,useHearth} from "./hearth-provider";
import {ContentState,RegistryNotice,SiteFooter,SiteHeader,SourceBadge} from "./site-shell";
import {SpiritPortrait} from "./illustrations";
import s from "./journey.module.css";

const LABELS:Record<PairEvaluation["status"],string>={eligible:"Promising introduction","needs-negotiation":"An agreement to make","needs-information":"A little more to ask",excluded:"A boundary comes first"};
function Status({status}:{status:PairEvaluation["status"]}){return <span className={[s.status,status==="needs-negotiation"?s.conditional:status==="excluded"?s.excluded:status==="needs-information"?s.unknown:""].join(" ")}>{status==="eligible"&&<Check size={11}/>} {LABELS[status]}</span>;}
function PairPortraits({spirits}:{spirits:Spirit[]}){return <div className={s.pairPortraits} style={{gridTemplateColumns:`repeat(${spirits.length}, minmax(0,1fr))`}}>{spirits.map(spirit=><div key={spirit.id}><SpiritPortrait kind={spirit.portrait}/></div>)}{spirits.length===2&&<span aria-hidden="true">&</span>}</div>;}
function pairPath(ids:string[]){return "/match/"+encodeURIComponent(ids.join("~"));}
function ScoreRow({evaluation,names}:{evaluation:PairEvaluation;names:string[]}){return <div className={s.scoreRow}>{evaluation.spiritIds.map((id,index)=><span key={id}>Home + {names[index].split(" ")[0]}<strong>{(evaluation.hostScores?.[id] ?? (index===0?evaluation.hostAScore:index===1?evaluation.hostBScore:null))??"?"}<small> / 100</small></strong></span>)}<span>{names.length===2?"The two spirits":"Resident relationships"}<strong>{evaluation.pairScore??"?"}<small> / 100</small></strong></span></div>;}

function NoHome(){return <div className={s.noHome}><span className="eyebrow">HOUSEHOLD APPLICATION</span><h1>Start with your <em>household.</em></h1><p>Choose a household application or tell us about your home. No names, addresses or perfect answers required.</p><Link className="button button-primary" href="/find">Household application <ArrowRight size={17}/></Link></div>;}
function currentHome(state:HearthState,home:HostPreferences){return home.templateId?state.homes.find(preset=>preset.id===home.templateId)?.preferences??home:home;}

function uniqueReasons(reasons:MatchReason[]){const seen=new Set<string>();return reasons.filter(reason=>{const key=reason.code+'\n'+reason.detail;if(seen.has(key))return false;seen.add(key);return true;});}
function pairIntroduction(text:string){
 const compact=text.replace(/\s+/g,' ').trim();
 const sentences=Array.from(new Intl.Segmenter('en',{granularity:'sentence'}).segment(compact),part=>part.segment.trim());
 const introduction=sentences.slice(0,2).join(' ');
 if(introduction.length<=230)return introduction;
 const wordEnd=introduction.lastIndexOf(' ',220);
 return introduction.slice(0,wordEnd>150?wordEnd:220).replace(/[,:;]$/,'')+'…';
}
function primaryHostReasons(evaluation:PairEvaluation){
 const hostReasons=[evaluation.hostAFactors,evaluation.hostBFactors].flatMap(factors=>[...factors].sort((a,b)=>Math.abs(b.impact??0)-Math.abs(a.impact??0)).slice(0,1));
 return uniqueReasons([...evaluation.exclusions,...evaluation.unknowns,...hostReasons,...evaluation.reasons]).slice(0,2);
}

function PairCard({evaluation,state,index}:{evaluation:PairEvaluation;state:HearthState;index:number}){
 const spirits=evaluation.spiritIds.map(id=>state.spirits.find(spirit=>spirit.id===id)!);
 const relationship=state.pairRelationships.find(pair=>evaluation.spiritIds.every(id=>pair.spiritIds.includes(id)));
 const explanations=primaryHostReasons(evaluation);
 return <article className={s.pairCard}><div className={s.pairTop}><span>GROUP {String(index+1).padStart(2,"0")}</span><Status status={evaluation.status}/></div><PairPortraits spirits={spirits}/><div className={s.pairBody}><h2>{spirits.map((spirit,index)=><span key={spirit.id}>{index>0&&<><em> & </em><br/></>}{spirit.name}</span>)}</h2>{relationship&&<p className={s.cardIntroduction}>{pairIntroduction(relationship.description)}</p>}<ScoreRow evaluation={evaluation} names={spirits.map(spirit=>spirit.name)}/><div className={s.pairMeta}>PREFERENCE COMPARISON</div><ul className={s.cardReasons}>{explanations.map((reason,index)=><li key={reason.code+index}>{reason.detail}</li>)}{evaluation.negotiations.some(clause=>!clause.accepted)&&<li>Quiet hours need an explicit agreement before an introduction can be reviewed.</li>}</ul><Link className="button" href={pairPath(evaluation.spiritIds)}>Review this group <ArrowRight size={16}/></Link></div></article>;
}
export function MatchesPage(){
 const {state,home,localReady}=useHearth();const [all,setAll]=useState(false);const [groupSize,setGroupSize]=useState(2);
 const result=useMemo(()=>{if(!state||!home)return {pairs:[],error:""};try{return {pairs:rankGroups(state,currentHome(state,home),[],groupSize),error:""};}catch(err){return {pairs:[],error:err instanceof Error?err.message:"The matching rules need review."};}},[state,home,groupSize]);
 const selected=state?.homes.find(preset=>preset.id===home?.templateId);
 const ready=result.pairs.filter(pair=>pair.status==="eligible"||pair.status==="needs-negotiation").length;
 return <><SiteHeader/><RegistryNotice/><main id="main" className={s.main}><ContentState>{!localReady?<div className="content-state" role="status">Restoring your visit...</div>:!home?<NoHome/>:<><div className={s.topline}><Link href="/find" className={s.quietLink}><ArrowLeft size={12}/> Your household answers</Link></div><div className={s.heading}><div><span className="eyebrow">YOUR HOUSEHOLD MATCHES</span><h1>Possible <em>company</em></h1></div><p>Each proposed group considers your household with each spirit,<br/>and every relationship within the departed group.</p></div><div className={s.resultsInfo}><p><strong>{selected?.name??"Your household"}</strong>{ready?ready+" groups are ready for a conversation or a specific agreement.":"There are questions or boundaries to resolve before an introduction."}</p><Link className="button button-small" href="/find">Review the household <ArrowRight size={14}/></Link></div>{result.error&&<p className={s.error} role="alert">{result.error}</p>}<fieldset style={{border:0,padding:"18px 0",display:"flex",gap:18,flexWrap:"wrap"}}><legend className="eyebrow">DEPARTED RESIDENTS IN THIS REVIEW</legend>{[2,3].map(size=><label key={size} style={{display:"flex",gap:8,alignItems:"center",fontSize:13}}><input type="radio" name="group-size" value={size} checked={groupSize===size} onChange={()=>{setGroupSize(size);setAll(false);}}/>{size} residents</label>)}<p style={{fontSize:12,lineHeight:1.8,width:"100%"}}>Nobody is placed alone. Browse two or three residents here; larger and family groups need the same individual care and relationship review. Living households may be one person, a couple, family or housemates.</p></fieldset><div className={s.resultsGrid}>{state&&result.pairs.slice(0,all?result.pairs.length:4).map((evaluation,index)=><PairCard key={evaluation.spiritIds.join(":")} evaluation={evaluation} state={state} index={index}/>)}</div>{result.pairs.length>4&&<button className={"button "+s.moreButton} onClick={()=>setAll(!all)}>{all?"Show the first four groups":"See all "+result.pairs.length+" groups, including boundaries"} <ArrowRight size={15}/></button>}<p className={s.methodNote}>A strong preference score never cancels a firm boundary. Unknown answers stay unknown. A quiet-hours agreement cannot invent a new time for company. Introduction questions, current consent and an agreed exit plan must be resolved before a trial stay can begin.</p></>}</ContentState><details className={s.demoDetails}><summary>Demo details</summary><SourceBadge/><p>Your answers and case reviews stay in this browser. No application or invitation is sent, and your decisions do not change the shared registry.</p><Link href="/about">About this service <ArrowRight size={12}/></Link></details></main><SiteFooter/></>;
}
function FactorGroup({title,score,factors}:{title:string;score:number|null;factors:MatchReason[]}){
 return <section className={s.factorGroup}><div className={s.factorHeading}><h3>{title}</h3><span>{score===null?"Unknown":score+" / 100"}</span></div><ul>{factors.map((factor,index)=><li key={factor.code+index}><strong>{factor.label}{factor.impact!==undefined?" · "+factor.impact+" points":""}</strong>{factor.detail}</li>)}</ul></section>;
}
function ReasonList({reasons}:{reasons:MatchReason[]}){return <ul className={s.reasonList}>{uniqueReasons(reasons).map((reason,index)=><li key={reason.code+index}><strong>{reason.label}</strong>{reason.detail}</li>)}</ul>;}
export function PairPage({pair}:{pair:string}){
 const {state,home,setHome,command,localReady,error:registryError}=useHearth();const router=useRouter();const [accepted,setAccepted]=useState(false);const [error,setError]=useState("");const [compareId,setCompareId]=useState("");const creating=useRef(false);
 const ids=pair.split("~");
 const effectiveHome=state&&home?currentHome(state,home):null;
 const evaluationResult=useMemo(()=>{if(!state||!effectiveHome)return {evaluation:null,base:null,error:""};try{return {evaluation:evaluatePair(state,{home:effectiveHome,spiritIds:ids,acceptedClauseIds:accepted?["quiet-hours"]:[]}),base:evaluatePair(state,{home:effectiveHome,spiritIds:ids,acceptedClauseIds:[]}),error:""};}catch(err){return {evaluation:null,base:null,error:err instanceof Error?err.message:"This proposed group could not be found."};}},[state,effectiveHome,pair,accepted]);
 const evaluation=evaluationResult.evaluation;const base=evaluationResult.base;
 const spirits=state?ids.map(id=>state.spirits.find(spirit=>spirit.id===id)).filter((spirit):spirit is Spirit=>!!spirit):[];
 const preset=state?.homes.find(preset=>preset.id===home?.templateId);
 const relationship=state?.pairRelationships.find(relationship=>ids.every(id=>relationship.spiritIds.includes(id)));
 const comparisonHome=state?.homes.find(preset=>preset.id===(compareId||state.homes.find(preset=>preset.id!==home?.templateId)?.id));
 let comparison:PairEvaluation|null=null;
 if(state&&comparisonHome&&spirits.length>=2){try{comparison=evaluatePair(state,{home:comparisonHome.preferences,spiritIds:ids});}catch{}}
 function openReview(){
  if(!evaluation||!effectiveHome||creating.current)return;
  creating.current=true;setError("");
  try{
   const existing=state?.placements.find(placement=>placement.status==="review"&&stableSerialize(placement.spiritIds)===stableSerialize(ids)&&stableSerialize(placement.home)===stableSerialize(effectiveHome)&&stableSerialize(placement.acceptedClauseIds)===stableSerialize(evaluation.acceptedClauseIds));
   if(existing){router.push("/stay/"+encodeURIComponent(existing.id));return;}
   const result=command({type:"create",requestId:newRequestId(),home:effectiveHome,spiritIds:ids,acceptedClauseIds:evaluation.acceptedClauseIds,sourceSnapshot:evaluation.sourceSnapshot});
   router.push("/stay/"+encodeURIComponent(result.placement.id));
  }catch(err){setError(err instanceof Error?err.message:"The review could not be opened.");creating.current=false;}
 }
 return <><SiteHeader/><RegistryNotice/><main id="main" className={s.main}><ContentState>{!localReady?<div className="content-state" role="status">Restoring your visit...</div>:!home?<NoHome/>:!evaluation||spirits.length<2?<div className={s.noHome}><span className="eyebrow">GROUP NOT AVAILABLE</span><h1>This group is <em>unavailable.</em></h1><p>{evaluationResult.error||"A resident in this group is no longer listed."}</p><Link className="button" href="/matches">Return to the groups <ArrowRight size={16}/></Link></div>:<><div className={s.topline}><Link className={s.quietLink} href="/matches"><ArrowLeft size={12}/> All possible company</Link></div><section className={s.reviewHero}><div><span className="eyebrow">GROUP REVIEW</span><h1>{spirits.map((spirit,index)=><span key={spirit.id}>{index>0&&<><br/><em>& </em></>}{spirit.name}</span>)}</h1><p>Considered for {preset?.name??"your household"}. What feels natural, what needs an agreement, and what remains a question.</p><div style={{marginTop:18}}><Status status={evaluation.status}/></div></div><PairPortraits spirits={spirits}/></section><div className={s.reviewGrid}><div><section className={s.panel}><span className="eyebrow">COMPATIBILITY</span><h2>Compatibility overview</h2><p>These points compare the household with every resident and review every relationship within the group. Firm boundaries and unanswered questions are considered separately; a high score cannot override them.</p>{spirits.map((spirit,index)=><FactorGroup key={spirit.id} title={"Home + "+spirit.name} score={evaluation.hostScores?.[spirit.id] ?? (index===0?evaluation.hostAScore:index===1?evaluation.hostBScore:null)} factors={evaluation.hostFactors?.[spirit.id]??(index===0?evaluation.hostAFactors:index===1?evaluation.hostBFactors:[])}/>)}<FactorGroup title="Relationships within the group" score={evaluation.pairScore} factors={evaluation.pairFactors}/></section>
 {(evaluation.exclusions.length>0||evaluation.unknowns.length>0)&&<section className={s.panel}><span className="eyebrow">BEFORE ANY INTRODUCTION</span><h2>{evaluation.exclusions.length?"Requirements that are not met":"Questions to resolve"}</h2><p>{evaluation.exclusions.length?"This group does not meet one or more firm requirements. Review them below or consider another group.":"Check these details before proceeding. Unanswered questions remain unresolved."}</p><ReasonList reasons={[...evaluation.exclusions,...evaluation.unknowns]}/></section>}
 {base&&base.negotiations.length>0&&<section className={s.panel}><span className="eyebrow">QUIET HOURS</span><h2>Quiet-hour agreement</h2><p>Some preferences can be adjusted by agreement. Firm boundaries stay firm, and everyone gives separate consent during the review.</p>{base.negotiations.map(clause=><label className={s.negotiation} key={clause.id}><input type="checkbox" checked={accepted} onChange={event=>{setAccepted(event.target.checked);setError("");}}/><span><strong>{clause.title}</strong><p>{clause.description}</p></span></label>)}{accepted&&<p className={s.delta}>Recalculated: {base.overallScore??"?"} → {evaluation.overallScore??"?"} preference points. {evaluation.status==="eligible"?"Ready to review an introduction.":"Other conditions still need attention."}</p>}</section>}
 {relationship&&<section className={s.panel+" "+s.pairStory}><span className="eyebrow">SHARING A HOME</span><h2>{relationship.title}</h2>{relationship.description.split(/\n\s*\n/).filter(Boolean).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</section>}<section className={s.panel}><span className="eyebrow">INTRODUCTIONS</span><h2>Before the introduction</h2><p>Discuss these questions together. Every required confirmation needs an answer before a trial begins.</p>{evaluation.introductionQuestions?.length?<ul className={s.reasonList}>{evaluation.introductionQuestions.map(question=><li key={question.spiritId+":"+question.id}><strong>{question.spiritName}: {question.question}</strong>{question.whyItMatters}</li>)}</ul>:<p style={{marginTop:15}}>The registry lists no additional introduction questions for this group. Consent and trial planning are still required.</p>}</section><section className={s.panel}><span className="eyebrow">THE SPIRITS</span><h2>Meet the departed residents</h2><ul className={s.reasonList}>{spirits.map(spirit=><li key={spirit.id}><strong>{spirit.name}</strong>{spirit.summary}<br/><Link className="underlined-link" href={"/spirits/"+encodeURIComponent(spirit.id)}>Read the full profile <ArrowRight size={12}/></Link></li>)}</ul></section></div>
 <aside className={s.sticky}><div className={s.decisionPanel}><ShieldCheck size={23}/><span className="eyebrow" style={{display:"block",marginTop:16}}>PLACEMENT REVIEW</span><h2>{evaluation.status==="eligible"?"Ready for a case review":"Review the outstanding requirements"}</h2><div className={s.decisionScore}>{evaluation.overallScore??"?"}<small>{evaluation.overallScore!==null?" / 100":""}</small></div><p>Preference comparison.<br/>{evaluation.status==="eligible"?"An introduction can be reviewed. A residential stay still needs every required answer, every required consent or assent and a complete plan.":"Resolve the stated conditions before opening an introduction. Nobody is obliged to change a boundary."}</p><button className="button" disabled={evaluation.status!=="eligible"||!!registryError} onClick={openReview}>Review an introduction <MessagesSquare size={16}/></button>{error&&<p className={s.error} role="alert">{error}</p>}</div><div className={s.comparison}><h3>Compare another household</h3><p>See how this group changes for another household.</p><label className="eyebrow" htmlFor="compare-home">COMPARE A HOUSEHOLD</label><select id="compare-home" value={comparisonHome?.id??""} onChange={event=>setCompareId(event.target.value)}>{state?.homes.filter(preset=>preset.id!==home?.templateId).map(preset=><option key={preset.id} value={preset.id}>{preset.name}</option>)}</select>{comparison&&<><Status status={comparison.status}/><ReasonList reasons={uniqueReasons([...comparison.exclusions,...comparison.unknowns,...comparison.reasons]).slice(0,2)}/><button className="underlined-link" style={{background:"transparent",borderTop:0,borderLeft:0,borderRight:0,marginTop:14}} onClick={()=>{if(comparisonHome){setHome(comparisonHome.preferences);setAccepted(false);setCompareId("");setError("");creating.current=false;window.scrollTo({top:0,behavior:"smooth"});}}}>Use this household <ArrowRight size={14}/></button></>}</div></aside></div></>}</ContentState><details className={s.demoDetails}><summary>Demo details</summary><SourceBadge/><p>Your answers and case reviews stay in this browser. No application or invitation is sent, and your decisions do not change the shared registry.</p><Link href="/about">About this service <ArrowRight size={12}/></Link></details></main><SiteFooter/></>;
}
