"use client";

import {useState, type ReactNode} from "react";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Check,CheckCircle2,ChevronDown,Clock3,DoorOpen,FileCheck2,Home,MessageCircle,RotateCcw,ShieldCheck,Sprout} from "lucide-react";
import type {ConsentParty,HearthState,PairEvaluation,Placement,PlacementCommand,RelocationPlan,TrialPlan} from "@/lib/hearth/domain";
import {PLACEMENT_STATUS_LABELS} from "@/lib/hearth/domain";
import {evaluatePair,stableSerialize} from "@/lib/hearth/matching";
import {consentRequirements,getIntroductionReadinessIssues,getPlacementReadinessIssues} from "@/lib/hearth/placement";
import {getSourceCorrections} from "@/lib/hearth/source-corrections";
import {newRequestId,useHearth} from "./hearth-provider";
import {SpiritPortrait} from "./illustrations";
import {ContentState,RegistryNotice,SiteFooter,SiteHeader,SourceBadge} from "./site-shell";
import {SavedCaseRecovery} from "./saved-case-recovery";
import s from "./placement-page.module.css";

type ExistingCommand=Exclude<PlacementCommand,{type:"create"}>;
type ReviewOperation<T=ExistingCommand>=T extends ExistingCommand?Omit<T,"requestId"|"placementId"|"expectedRev">:never;
type Run=(operation:ReviewOperation,message:string)=>boolean;

const DEFAULT_TRIAL:TrialPlan={durationDays:14,checkInDays:[2,7,14],successCriteria:"Everyone feels able to join in, retreat, and ask for changes without pressure."};
const DEFAULT_RELOCATION:RelocationPlan={destination:"The Willow House guest rooms",coordinator:"OLDA duty placement coordinator",trigger:"Anyone asks to end the stay or a shared boundary cannot be maintained.",handoverNotes:"Confirm a private room, arrange the move, and check in with each resident separately."};
function dateLabel(value:string){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(value));}
function SectionHeading({number,title,children}:{number:string;title:string;children:ReactNode}){return <div className={s.sectionHeading}><span className={s.sectionNumber}>{number}</span><div><h2>{title}</h2><p>{children}</p></div></div>;}

export function PlacementPage({id}:{id:string}){
 const {state,localReady,savedPlacements,error}=useHearth();
 const placement=savedPlacements.find(entry=>entry.id===id);
 if(localReady&&placement&&(!state||error))return <><SiteHeader/><RegistryNotice/><main id="main" className={s.main}><SavedCaseRecovery key={placement.id} placement={placement}/></main><SiteFooter/></>;
 return <><SiteHeader/><RegistryNotice/><main id="main" className={s.main}><ContentState>{!localReady?<div className="content-state" role="status"><h1>Opening your case.</h1><p>Restoring this browser's saved visit.</p></div>:placement&&state?<PlacementReview key={placement.id} placement={placement} state={state}/>:<div className={s.empty}><DoorOpen size={38}/><span className="eyebrow">CASE REVIEW</span><h1>Case not found</h1><p>This case is not saved in this browser. Start with a household application to open a new review.</p><Link href="/find" className="button button-pine">Find your company <ArrowRight size={16}/></Link></div>}</ContentState></main><SiteFooter/></>;
}

function PlacementReview({placement,state}:{placement:Placement;state:HearthState}){
 const {command,reload,error:registryError}=useHearth();
 const [feedback,setFeedback]=useState<{kind:"success"|"error";text:string}|null>(null);
 const [planDirty,setPlanDirty]=useState(false);
 const [outcome,setOutcome]=useState("");
 const [exitNote,setExitNote]=useState("");
 const [handoverNote,setHandoverNote]=useState("");
 const [refreshing,setRefreshing]=useState(false);
 const spirits=placement.spiritIds.map(id=>state.spirits.find(spirit=>spirit.id===id));
 const names=spirits.map((spirit,index)=>spirit?.name??`Spirit ${index+1}`);
 const household=state.homes.find(home=>home.id===placement.home.templateId);
 const isReview=placement.status==="review";
 const isActive=placement.status==="trial"||placement.status==="settled";
 const questions=placement.evaluation.introductionQuestions??[];
 const answers=placement.answers??[];
 const introductionsReady=getIntroductionReadinessIssues(placement).length===0;
 let currentSources=false;
 try{currentSources=stableSerialize(evaluatePair(state,{home:placement.home,spiritIds:placement.spiritIds,acceptedClauseIds:placement.acceptedClauseIds}).sourceSnapshot)===stableSerialize(placement.evaluation.sourceSnapshot);}catch{/* The readiness list explains unavailable source records. */}
 const corrections=getSourceCorrections(state,placement);
 const issues=getPlacementReadinessIssues(state,placement);
 if(registryError)issues.unshift("Reconnect to the registry before starting or settling a stay. Refusal, withdrawal, and a safe exit remain available.");
 if(isReview&&planDirty)issues.unshift("Save the edited plan before recording decisions or starting a trial.");
 const planSaved=Boolean(placement.trialPlan&&placement.relocationPlan);
 const mayAgree=isReview&&planSaved&&!planDirty&&introductionsReady&&currentSources&&!registryError;
 const events=state.events.filter(event=>event.placementId===placement.id).slice().reverse();
 function run(operation:ReviewOperation,message:string){
  try{command({...operation,placementId:placement.id,expectedRev:placement.rev,requestId:newRequestId()} as PlacementCommand);setFeedback({kind:"success",text:message});return true;}
  catch(error){setFeedback({kind:"error",text:error instanceof Error?error.message:"This change could not be recorded. Please try again."});return false;}
 }
 async function refreshRegistry(){setRefreshing(true);await reload();setRefreshing(false);}
 const heroTitle={review:<>Placement <em>review</em></>,trial:<>Trial <em>stay</em></>,settled:<>Settled <em>placement</em></>,declined:<>Introduction <em>declined</em></>,relocating:<>Relocation <em>plan</em></>,closed:<>Case <em>closed</em></>}[placement.status];
 return <>
  <div className={s.topline}><Link href="/matches" className={s.back}><ArrowLeft size={14}/> Back to possible company</Link></div>
  <header className={s.heading}><div><span className="eyebrow">OLDA / VOLUNTARY PLACEMENT REVIEW</span><h1>{heroTitle}</h1><p>Review the plan, required questions, and each party&apos;s decision.<br/>Everyone keeps the right to decline or leave.</p></div><div className={s.caseStamp}><FileCheck2 size={27}/><span>CASE {placement.id.slice(-6).toUpperCase()}</span><strong>{PLACEMENT_STATUS_LABELS[placement.status]}</strong></div></header>

  <div className={s.layout}>
   <aside className={s.sidebar}>
    <div className={s.household}><Home size={18}/><div><span className="eyebrow">THE PROPOSED HOUSEHOLD</span><h2>{household?.name??"Your household"}</h2><p>{household?.subtitle??"Household application"}</p></div></div>
    <div className={s.pair}>{spirits.map((spirit,index)=><div className={s.person} key={placement.spiritIds[index]}>{spirit&&<SpiritPortrait kind={spirit.portrait}/>}<div><span>0{index+1} / THE DEPARTED</span><h3>{names[index]}</h3><p>{spirit?.formerOccupation??"Profile unavailable"}</p>{spirit&&<Link href={`/spirits/${spirit.id}`}>Revisit profile <ArrowRight size={12}/></Link>}</div></div>)}</div>
    <div className={s.sideNote}><Sprout size={22}/><h3>About this review</h3><p>A proposed group still needs a shared plan, individual decisions, and a safe way to end the stay.</p></div>
    <nav className={s.contents} aria-label="Case sections"><a href="#plan">The shared plan <ArrowRight size={12}/></a><a href="#introductions">First conversations <ArrowRight size={12}/></a><a href="#consents">Separate decisions <ArrowRight size={12}/></a><a href="#next-step">The next step <ArrowRight size={12}/></a><a href="#case-notes">Case notes <ArrowRight size={12}/></a></nav>
    <div className={s.sourceNote} id="registry-review"><p>Preferences and boundaries can change. Check the current registry before taking the next step.</p><button disabled={refreshing} onClick={()=>void refreshRegistry()}><RotateCcw size={12}/>{refreshing?"Checking registry...":"Check registry for changes"}</button></div>
   </aside>
   <div className={s.content}>
    {feedback&&<div className={feedback.kind==="error"?s.error:s.feedback} role={feedback.kind==="error"?"alert":"status"}>{feedback.kind==="success"&&<CheckCircle2 size={17}/>}<span>{feedback.text}</span></div>}
    {corrections.stale&&(isReview||isActive)&&<div className={s.notice} id="registry-changes"><ShieldCheck size={19}/><div><h3>{corrections.changes.length?"Review the changed household terms":"Review the current records"}</h3><p>{corrections.notice}</p>{corrections.changes.length>0&&<div className={s.changedTerms}>{corrections.changes.map(change=><section key={change.field}><h4>{change.label}</h4><dl><div><dt>Saved in this review</dt><dd>{change.before}</dd></div><div><dt>Current household terms</dt><dd>{change.after}</dd></div></dl></section>)}</div>}<p>{isReview?"Review the current terms before recording a decision. Updating this review clears introduction answers and all required decisions.":"Review the changed details before settling this stay. Its agreed safe exit remains available."}</p>{isReview&&<button className={s.textButton} disabled={Boolean(registryError)} onClick={()=>run({type:"refresh-review",acceptedClauseIds:placement.acceptedClauseIds},"Current records reviewed. Please revisit introductions and collect fresh decisions from everyone.")}>Review latest records <RotateCcw size={13}/></button>}</div></div>}
    <section id="plan" className={s.section}><SectionHeading number="01" title="Trial and relocation plan">Agree on the trial period, check-ins, and relocation arrangements.</SectionHeading><PlanForm key={JSON.stringify([placement.trialPlan,placement.relocationPlan])} placement={placement} editable={isReview} run={run} onDirtyChange={setPlanDirty}/></section>
    <section id="introductions" className={s.section}><SectionHeading number="02" title="Introduction questions">Discuss the outstanding questions with the household and every departed resident.</SectionHeading>{questions.length?<div className={s.questions}>{questions.map(question=><IntroductionQuestion key={`${question.spiritId}-${question.id}-${placement.evaluation.sourceSnapshot.fingerprint}`} question={question} saved={answers.find(answer=>answer.spiritId===question.spiritId&&answer.questionId===question.id)} editable={isReview&&planSaved&&!planDirty&&currentSources&&!registryError} run={run}/>)}</div>:<p className={s.smallNote}>No additional introduction questions are attached to these profiles.</p>}{isReview&&<p className={s.smallNote}>{!planSaved||planDirty?"Save the shared plan first. Then record the conversations below.":"Required questions need a current yes before a trial can begin. No and still unknown keep the review open; they do not record a refusal."}</p>}</section>
    <section id="consents" className={s.section}><SectionHeading number="03" title="Consent decisions">Every adult decides independently. Children remain with their documented departed guardian: guardian care agreement and age-appropriate assent are separate records. A child's refusal is never replaced by an adult yes.</SectionHeading><div className={s.consentGrid}>{consentRequirements(placement).map(requirement=><ConsentCard key={requirement.party} party={requirement.party} name={requirement.kind==="adult"?state.spirits.find(spirit=>spirit.id===requirement.spiritId)?.name??requirement.label:requirement.label} record={placement.consents[requirement.party]??{decision:"pending",at:null,note:""}} mayAgree={mayAgree} mayRefuse={isReview||isActive} active={isActive} run={run}/>)}</div>{isReview&&!mayAgree&&<p className={s.smallNote}>Save the plan, answer required introduction questions, and review current records before recording agreement. A refusal remains available.</p>}<p className={s.consentRule}><ShieldCheck size={15}/> A refusal ends this proposal. Editing the plan or introduction answers clears the previous agreements.</p></section>
    <section id="next-step" className={`${s.section} ${s.nextStep}`}>
     <div className={s.nextHeading}><DoorOpen size={26}/><span className="eyebrow">THE NEXT STEP</span><span className={s.status}>{PLACEMENT_STATUS_LABELS[placement.status]}</span></div>
     {isReview&&<><h2>Ready to begin the trial?</h2><p>Begin a {placement.trialPlan?.durationDays??14}-day trial stay once the shared plan, introductions, and all required decisions are complete.</p>{issues.length>0?<ReadinessSummary placement={placement} issues={issues} title="Before this trial can begin"/>:<div className={s.ready}><CheckCircle2 size={18}/> The plan is ready and all required parties have independently agreed.</div>}<button className="button button-pine" disabled={issues.length>0} onClick={()=>run({type:"transition",to:"trial",note:"Trial stay opened after the shared plan, introduction answers, and every required independent decision were reviewed."},"The trial stay has begun. Record the outcome after reviewing the check-ins.")}>Begin trial stay <ArrowRight size={16}/></button><details className={s.exit}><summary>Close this review without a stay <ChevronDown size={14}/></summary><label>Reason for closing<textarea value={exitNote} onChange={event=>setExitNote(event.target.value)} placeholder="Explain why this review is ending." minLength={12} maxLength={2000}/></label><button className="button button-small" disabled={exitNote.trim().length<12} onClick={()=>run({type:"transition",to:"closed",note:exitNote},"The review is closed.")}>Close review</button><small>At least 12 characters. A closed review stays closed.</small></details></>}
     {placement.status==="trial"&&<><h2>Record the trial outcome</h2><p>Review the planned check-ins. Describe what the household and every departed resident learned before recording the trial outcome.</p><div className={s.checkIns}>{placement.trialPlan?.checkInDays.map(day=><span key={day}><Clock3 size={13}/> Day {day}</span>)}</div><label className={s.outcome}>Trial outcome<textarea value={outcome} onChange={event=>setOutcome(event.target.value)} minLength={20} maxLength={2000} placeholder="What worked, what changed, and why do all required parties want to continue?"/></label><small className={s.counter}>{outcome.trim().length}/20 minimum characters</small>{issues.length>0&&<ReadinessSummary placement={placement} issues={issues} title="This case needs attention"/>}<button className="button button-pine" disabled={outcome.trim().length<20||issues.length>0} onClick={()=>run({type:"transition",to:"settled",note:outcome},"The household is settled. The right to leave remains open.")}>Record trial outcome <Check size={16}/></button></>}
     {placement.status==="settled"&&<><h2>Your placement is settled</h2><p>The trial outcome has been recorded. Boundaries still matter, and each party keeps the right to end the stay.</p><blockquote className={s.outcomeQuote}>{placement.note}</blockquote></>}
     {placement.status==="declined"&&<><h2>The introduction was declined</h2><p>A party declined this proposal. Their refusal is preserved and this arrangement cannot be reopened. You can close the record or explore a different match.</p><blockquote className={s.outcomeQuote}>{placement.note}</blockquote><label className={s.outcome}>Closing note<textarea value={exitNote} onChange={event=>setExitNote(event.target.value)} minLength={12} maxLength={2000} placeholder="Record how the refusal was respected."/></label><button className="button" disabled={exitNote.trim().length<12} onClick={()=>run({type:"transition",to:"closed",note:exitNote},"The declined proposal is now closed; its decisions remain in the case notes.")}>Close declined case</button><p className={s.smallNote}>At least 12 characters.</p></>}
     {placement.status==="relocating"&&<><h2>Complete the handover</h2><p>Follow the agreed relocation plan above, keeping dependent residents with their guardians and existing families together. Close the case when a safe destination and the completed handover are recorded.</p><label className={s.outcome}>Handover outcome<textarea value={handoverNote} onChange={event=>setHandoverNote(event.target.value)} minLength={12} maxLength={2000} placeholder="Where did each person go, and how was the handover completed?"/></label><button className="button button-pine" disabled={handoverNote.trim().length<12} onClick={()=>run({type:"transition",to:"closed",note:handoverNote},"The handover is recorded and this case is closed.")}>Record handover & close <Check size={16}/></button><p className={s.smallNote}>At least 12 characters.</p></>}
     {placement.status==="closed"&&<><h2>This case is closed</h2><p>This case is closed. Its plan, decisions, and case notes remain available here.</p><blockquote className={s.outcomeQuote}>{placement.note}</blockquote><Link href="/matches" className="button">Explore possible company <ArrowRight size={16}/></Link></>}
     {isActive&&<details className={s.exit}><summary>Arrange a safe relocation <ChevronDown size={14}/></summary><p>Leaving is always an option. The saved plan names the next place and responsible coordinator.</p><label>Reason and next steps<textarea value={exitNote} onChange={event=>setExitNote(event.target.value)} minLength={12} maxLength={2000} placeholder="Explain what changed and how the agreed relocation will be arranged."/></label><button className="button" disabled={exitNote.trim().length<12} onClick={()=>run({type:"transition",to:"relocating",note:exitNote},"The relocation is underway. Record the handover when ready.")}>Begin safe relocation <ArrowRight size={15}/></button><small>At least 12 characters.</small></details>}
    </section>
    <section id="case-notes" className={`${s.section} ${s.audit}`}><div className={s.auditHeading}><div><span className="eyebrow">CASE NOTES</span><h2>Case history</h2></div><div className={s.auditActions}><span>{events.length} {events.length===1?"entry":"entries"}</span><Link className={s.caseRecordLink} href={"/stay/"+encodeURIComponent(placement.id)+"/record"}>View case record <ArrowRight size={14}/></Link></div></div><p>Your decisions, updates, and next steps are recorded here.</p><ol className={s.timeline}>{events.map(event=><li key={event.id}><span className={s.timelineDot}/><div><div className={s.eventHeading}><strong>{event.action==="create"?"Review opened":event.action==="set-plan"?"Shared plan saved":event.action==="record-answer"?"Introduction answer recorded":event.action==="record-consent"?"Independent decision recorded":event.action==="refresh-review"?"Registry details reviewed":PLACEMENT_STATUS_LABELS[event.toStatus]}</strong><time dateTime={event.at}>{dateLabel(event.at)}</time></div><p>{event.note}</p></div></li>)}</ol></section>
   </div>
  </div>
  <details className={s.demoDetails}><summary>Demo details</summary><SourceBadge/><p>Your answers and case reviews stay in this browser. No application or invitation is sent, and your decisions do not change the shared registry. You can record the trial outcome without waiting for calendar days; this does not verify that a real stay took place.</p><Link href="/about">About this service <ArrowRight size={12}/></Link></details>
 </>;
}


function introductionAnchor(question:PairEvaluation['introductionQuestions'][number]){return 'introduction-'+question.spiritId+'-'+question.id;}
function ReadinessSummary({placement,issues,title}:{placement:Placement;issues:string[];title:string}){
 const questions=placement.evaluation.introductionQuestions??[];
 const introductionIssues=getIntroductionReadinessIssues(placement);
 const unresolved=questions.map((question,index)=>({question,index,answer:placement.answers.find(answer=>answer.questionId===question.id&&answer.spiritId===question.spiritId)})).filter(({question,answer})=>question.requiredForTrial&&!(answer?.answer==='yes'&&answer.sourceFingerprint===placement.evaluation.sourceSnapshot.fingerprint));
 const otherIssues=issues.filter(issue=>!introductionIssues.some(introductionIssue=>issue.includes(introductionIssue)));
 function issueTarget(issue:string){if(/registry|source|records|reconnect/i.test(issue))return '#registry-review';if(/consent|agreement|decision/i.test(issue))return '#consents';return '#plan';}
 return <div className={s.readiness}><h3>{title}</h3>{unresolved.length>0&&<div className={s.conversationSummary}><p><strong>{unresolved.length} {unresolved.length===1?'conversation needs':'conversations need'} confirmation</strong></p><p>Select a question to review the answer with the people involved.</p><ul className={s.questionJumps}>{unresolved.map(({question,index,answer})=><li key={question.spiritId+question.id}><a href={'#'+encodeURIComponent(introductionAnchor(question))} aria-label={'Question '+(index+1)+': '+question.question}><span>{String(index+1).padStart(2,'0')} · {question.spiritId.startsWith('spirit_')?question.spiritName.split(' ')[0]:'Household'}</span><small>{answer?.answer==='no'?'Not met':answer&&answer.sourceFingerprint!==placement.evaluation.sourceSnapshot.fingerprint?'Review again':'Not yet confirmed'}</small></a></li>)}</ul></div>}{otherIssues.length>0&&<ul className={s.otherRequirements}>{otherIssues.map((issue,index)=><li key={index}><a href={issueTarget(issue)}>{issue}</a></li>)}</ul>}</div>;
}

function PlanForm({placement,editable,run,onDirtyChange}:{placement:Placement;editable:boolean;run:Run;onDirtyChange:(value:boolean)=>void}){
 const [trial,setTrial]=useState<TrialPlan>(placement.trialPlan??DEFAULT_TRIAL);
 const [checkIns,setCheckIns]=useState((placement.trialPlan??DEFAULT_TRIAL).checkInDays.join(", "));
 const [relocation,setRelocation]=useState<RelocationPlan>(placement.relocationPlan??DEFAULT_RELOCATION);
 function changeTrial<K extends keyof TrialPlan>(key:K,value:TrialPlan[K]){setTrial(current=>({...current,[key]:value}));onDirtyChange(true);}
 function changeRelocation(key:keyof RelocationPlan,value:string){setRelocation(current=>({...current,[key]:value}));onDirtyChange(true);}
 const saved=Boolean(placement.trialPlan&&placement.relocationPlan);
 if(!editable)return <div className={s.planSummary}><div className={s.summaryHeading}><Clock3 size={18}/><h3>{placement.trialPlan?`${placement.trialPlan.durationDays} days to find a rhythm`:"No trial plan was saved"}</h3></div>{placement.trialPlan&&<><div className={s.checkIns}>{placement.trialPlan.checkInDays.map(day=><span key={day}>Check-in on day {day}</span>)}</div><p>{placement.trialPlan.successCriteria}</p></>}{placement.relocationPlan&&<><h3 className={s.relocationTitle}><DoorOpen size={17}/> Relocation arrangements</h3><dl className={s.planDetails}><div><dt>Next place</dt><dd>{placement.relocationPlan.destination}</dd></div><div><dt>Coordinator</dt><dd>{placement.relocationPlan.coordinator}</dd></div><div><dt>When to leave</dt><dd>{placement.relocationPlan.trigger}</dd></div><div><dt>Handover</dt><dd>{placement.relocationPlan.handoverNotes}</dd></div></dl></>}</div>;
 return <form className={s.planForm} onSubmit={event=>{event.preventDefault();const days=checkIns.split(",").map(day=>Number(day.trim()));if(run({type:"set-plan",trialPlan:{...trial,checkInDays:days},relocationPlan:relocation},"The plan is saved. Review introductions, then collect every required independent decision."))onDirtyChange(false);}}>
  <div className={s.formSubheading}><Clock3 size={18}/><h3>The trial stay</h3><span>{saved?"SAVED PLAN":"DRAFT PLAN"}</span></div>
  <div className={s.formRow}><label>Trial length <span>7 to 30 days</span><input type="number" min={7} max={30} required value={trial.durationDays} onChange={event=>changeTrial("durationDays",Number(event.target.value))}/></label><label>Check-in days <span>Comma separated, including the final day</span><input type="text" required value={checkIns} onChange={event=>{setCheckIns(event.target.value);onDirtyChange(true);}} placeholder="2, 7, 14"/></label></div>
  <label>What would a good trial look like?<textarea value={trial.successCriteria} required minLength={20} maxLength={1500} onChange={event=>changeTrial("successCriteria",event.target.value)}/><small>At least 20 characters. Describe comfort, boundaries, and everyone's freedom to choose.</small></label>
  <div className={`${s.formSubheading} ${s.relocationTitle}`}><DoorOpen size={18}/><h3>Relocation arrangements</h3><span>AGREED BEFORE ARRIVAL</span></div>
  <div className={s.formRow}><label>Next place<input value={relocation.destination} required minLength={5} maxLength={1500} onChange={event=>changeRelocation("destination",event.target.value)}/></label><label>Responsible coordinator<input value={relocation.coordinator} required minLength={3} maxLength={1500} onChange={event=>changeRelocation("coordinator",event.target.value)}/></label></div>
  <label>When should this plan be used?<textarea value={relocation.trigger} required minLength={12} maxLength={1500} onChange={event=>changeRelocation("trigger",event.target.value)}/></label><label>How will the handover work?<textarea value={relocation.handoverNotes} required minLength={12} maxLength={1500} onChange={event=>changeRelocation("handoverNotes",event.target.value)}/></label>
  <div className={s.savePlan}><button type="submit" className="button button-pine"><FileCheck2 size={16}/>{saved?"Save shared plan":"Save trial & relocation plan"}</button><p>Changing this plan clears introduction answers and all required decisions, so everyone can review the new terms.</p></div>
 </form>;
}

function IntroductionQuestion({question,saved,editable,run}:{question:PairEvaluation["introductionQuestions"][number];saved:Placement["answers"][number]|undefined;editable:boolean;run:Run}){
 const [note,setNote]=useState("");
 const labels={yes:"Yes",no:"No",unknown:"Still unknown"};
 function record(answer:"yes"|"no"|"unknown"){
  const defaultNote=answer==="yes"?`Introduction: the household and ${question.spiritName} confirm this condition is met.`:answer==="no"?`Introduction: this condition cannot currently be met for ${question.spiritName}.`:`Introduction: this condition still needs a conversation with ${question.spiritName}.`;
  run({type:"record-answer",spiritId:question.spiritId,questionId:question.id,answer,note:note.trim()||defaultNote},"Introduction answer recorded. Collect fresh consent if an answer changed.");
 }
 return <article id={introductionAnchor(question)} tabIndex={-1} className={s.question} aria-label={`${question.spiritName}: ${question.question}`}><div className={s.questionTop}><span><MessageCircle size={13}/> To confirm with {question.spiritName}</span><span>{question.requiredForTrial?"REQUIRED FOR A TRIAL":"FOR YOUR CONVERSATION"}</span></div><h3>{question.question}</h3><p>{question.whyItMatters}</p>{saved&&<div className={s.answerRecord}><strong>{labels[saved.answer]}</strong><span>{saved.note}</span></div>}{editable&&<><label className={s.optionalNote}>Conversation note <span>Add a note, if useful</span><textarea aria-label={`Conversation note for ${question.spiritName}: ${question.question}`} value={note} onChange={event=>setNote(event.target.value)} minLength={5} maxLength={1500} placeholder="Add what was discussed in this introduction."/></label><div className={s.answerButtons}>{(["yes","no","unknown"] as const).map(answer=><button key={answer} aria-label={`Record ${labels[answer].toLowerCase()} for ${question.spiritName}: ${question.question}`} className={saved?.answer===answer?s.answerSelected:s.answerButton} aria-pressed={saved?.answer===answer} disabled={Boolean(note.trim()&&note.trim().length<5)} onClick={()=>record(answer)}>{answer==="yes"&&<Check size={13}/>}Record {labels[answer].toLowerCase()}</button>)}</div></>}</article>;
}

function ConsentCard({party,name,record,mayAgree,mayRefuse,active,run}:{party:ConsentParty;name:string;record:Placement["consents"][ConsentParty];mayAgree:boolean;mayRefuse:boolean;active:boolean;run:Run}){
 const [note,setNote]=useState("");
 const decisionLabel={pending:"Awaiting a decision",granted:"Agreement recorded",denied:"Refusal recorded"}[record.decision];
 function decide(decision:"granted"|"denied"){
  const defaultNote=decision==="granted"?`Decision: ${name} ${party.startsWith("assent-")?"expresses age-appropriate assent":party.startsWith("guardian-")?"records the guardian care agreement":"independently agrees"} to the saved trial and relocation plan.`:`Decision: ${name} freely ${active?"withdraws from":"declines"} this arrangement.`;
  run({type:"record-consent",party,decision,note:note.trim()||defaultNote},decision==="granted"?`${name}'s agreement is recorded.`:active?"The refusal is respected. The case has moved to safe relocation.":"The refusal is respected. This proposal is now declined and cannot be reopened.");
 }
 return <article aria-label={`Decision for ${name}`} className={`${s.consent} ${record.decision==="granted"?s.agreed:record.decision==="denied"?s.denied:""}`}><span className={s.partyLabel}>{party==="household"?"THE LIVING":"THE DEPARTED"}</span><h3>{name}</h3><div className={s.decision}>{record.decision==="granted"?<CheckCircle2 size={15}/>:<span className={s.decisionDot}/>} {decisionLabel}</div>{record.note&&<p className={s.savedDecision}>{record.note}</p>}{record.at&&<time className={s.decisionTime} dateTime={record.at}>{dateLabel(record.at)}</time>}{mayRefuse&&<><label>Decision note <span>optional</span><textarea aria-label={`Decision note for ${name}`} value={note} onChange={event=>setNote(event.target.value)} minLength={5} maxLength={1500} placeholder="Record an adult decision, guardian care agreement or age-appropriate child assent in their own terms."/></label><div className={s.consentButtons}>{!active&&<button aria-label={`Record agreement for ${name}`} className="button button-small button-pine" disabled={!mayAgree||Boolean(note.trim()&&note.trim().length<5)} onClick={()=>decide("granted")}>Record agreement <Check size={13}/></button>}<button aria-label={`Record ${active?"withdrawal":"refusal"} for ${name}`} className={s.refuse} disabled={Boolean(note.trim()&&note.trim().length<5)} onClick={()=>decide("denied")}>{active?"Record withdrawal":"Record refusal"}</button></div></>}</article>;
}
