"use client";
import {useState} from "react";
import Link from "next/link";
import {ArrowUpRight,GitBranch} from "lucide-react";
import {useHearth} from "./hearth-provider";
export function RegistryExplorer(){
 const {state,error}=useHearth();const [selected,setSelected]=useState("spirit_iona_vale");
 if(!state)return <p>The registry must load before its linked records can be explored.</p>;
 const spirit=state.spirits.find(item=>item.id===selected)||state.spirits[0];if(!spirit)return null;
 const groups=[{title:"Life history",records:state.histories.filter(item=>spirit.historyIds.includes(item.id)).map(item=>({id:item.id,title:item.title,detail:item.era}))},{title:"Traits",records:state.traits.filter(item=>spirit.traitIds.includes(item.id)).map(item=>({id:item.id,title:item.label,detail:item.description}))},{title:"Boundaries",records:state.boundaries.filter(item=>spirit.boundaryIds.includes(item.id)).map(item=>({id:item.id,title:item.label,detail:item.kind==="hard"?"Firm boundary, checked before scoring":"Discuss and agree before a trial"}))},{title:"Resident relationships",records:state.pairRelationships.filter(item=>item.spiritIds.includes(spirit.id)).map(item=>({id:item.id,title:item.spiritIds.filter(id=>id!==spirit.id).map(id=>state.spirits.find(other=>other.id===id)?.name||"Unavailable record").join(", "),detail:item.status==="unacquainted"?"An introduction is still needed":item.status==="do-not-pair"?"Do not pair":"Recorded friendly relationship"}))}];
 return <div className="registry-explorer"><div className="explorer-heading"><GitBranch size={22}/><div><h3>Explore the linked records</h3><p>Choose a person to follow the history, shared traits, boundaries and relationships referenced by their current published profile.</p></div></div>{error&&<p role="status">The last loaded records are shown. Reconnect before relying on them.</p>}<div className="explorer-select"><label htmlFor="registry-spirit">Registered spirit</label><select id="registry-spirit" value={spirit.id} onChange={event=>setSelected(event.target.value)}>{state.spirits.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></div><div className="explorer-root"><div><span>SPIRIT PROFILE</span><strong>{spirit.name}</strong><small>{spirit.formerOccupation} / {spirit.pronouns}</small></div><Link href={`/spirits/${spirit.id}`}>Open profile <ArrowUpRight size={14}/></Link></div><div className="explorer-branches">{groups.map(group=><div key={group.title}><h4>{group.title}<span>{group.records.length}</span></h4>{group.records.length?<ul>{group.records.map(record=><li key={record.id}><strong>{record.title}</strong><span>{record.detail}</span></li>)}</ul>:<p>No linked record.</p>}</div>)}</div><p className="explorer-footnote">These are direct references and relationship edges in the loaded registry. Every relationship edge concerns two residents; a placement group can contain more than two. Shared references keep biographies, boundaries and matching explanations connected; this is not a list of every affected case.</p></div>;
}
